### ISSUE TITLE
EstructuraLibreria

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo_eaaj#1]
[PRACTICA_4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-equipo_eaaj/files/14653691/PRACTICA_4.pdf)

**Comment by AricelCastro** [comment]
Calificación 18.5/20 le faltan algunas imágenes

**Comment by josealfredo79** [comment]
bien hecho y revisado...
